return {
	"ThePrimeagen/vim-be-good",
	require("plugins/compile-mode"),
	require("plugins/cmake"),
	require("plugins/oil"),
	require("plugins/harpoon"),
	require("plugins/gitsigns"),
	require("plugins/which-key"),
	require("plugins/telescope"),
	require("plugins/nvim-lspconfig"),
	require("plugins/conform"),
	require("plugins/nvim-cmp"),
	require("plugins/theme"),
	require("plugins/mini"),
	require("plugins/nvim-treesitter"),
	require("plugins/dap"),
}
